
#!/bin/bash
set -e
psql -v ERROR_STOP=1 \
-v password = "$DATABASE_PASSWORRD" --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<- EOSQL
CREATE USER cs548user PASSWORD :'password';
CREATE DATABASE cs548 WITH OWNER cs548user;
GRANT ALL PRIVILEGES ON DATABASE cs548 TO cs548user;
EOSQL
